/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type ReportDto = {
    /**
     * Report UUID
     */
    id: string;
    /**
     * Profile id this report belongs to
     */
    profile_id: number;
    /**
     * Job id that produced this report
     */
    job_id: Record<string, any> | null;
    /**
     * Main LLM text (narrative/outlook)
     */
    content: Record<string, any> | null;
    /**
     * Confidence score
     */
    confidence: Record<string, any> | null;
    /**
     * LLM model used
     */
    llmModel: Record<string, any> | null;
    /**
     * Creation timestamp (ISO 8601)
     */
    created_at: string;
    /**
     * Kind/category of report
     */
    kind: string;
    /**
     * Relevance to the profile/topic (0..1)
     */
    relevance: Record<string, any> | null;
    /**
     * Input tokens used by the LLM
     */
    tokens_in: Record<string, any> | null;
    /**
     * Output tokens generated by the LLM
     */
    tokens_out: Record<string, any> | null;
    /**
     * Approximate processing cost (USD)
     */
    cost: Record<string, any> | null;
    /**
     * Short bullet-point summary
     */
    summary_bullets: Array<string> | null;
    /**
     * Key signals or insights
     */
    signals: Array<string> | null;
    /**
     * Risks or caveats
     */
    risks: Array<string> | null;
    /**
     * Overall sentiment label
     */
    sentiment_label: ReportDto.sentiment_label | null;
    /**
     * Numeric sentiment score
     */
    sentiment_score: number | null;
    /**
     * Forward-looking outlook text
     */
    outlook: string | null;
    /**
     * Citations with documentId and quote
     */
    support: Array<Record<string, any>> | null;
};
export namespace ReportDto {
    /**
     * Overall sentiment label
     */
    export enum sentiment_label {
        BEARISH = 'bearish',
        NEUTRAL = 'neutral',
        BULLISH = 'bullish',
    }
}

