/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type ReportCreateDto = {
    /**
     * Profile id to attach report to
     */
    profile_id: number;
    /**
     * Main LLM text (narrative/outlook)
     */
    content?: Record<string, any>;
    /**
     * LLM model used
     */
    llmModel?: Record<string, any>;
    /**
     * Job id that produced this report
     */
    job_id?: Record<string, any>;
    /**
     * Confidence score
     */
    confidence?: Record<string, any>;
    /**
     * Kind/category of report
     */
    kind?: string;
    /**
     * How relevant this report is to the profile/topic (0..1)
     */
    relevance?: Record<string, any>;
    /**
     * Number of input tokens used by the LLM
     */
    tokens_in?: Record<string, any>;
    /**
     * Number of output tokens generated by the LLM
     */
    tokens_out?: Record<string, any>;
    /**
     * Approximate processing cost (USD)
     */
    cost?: Record<string, any>;
    /**
     * Short bullet-point summary generated by the model
     */
    summary_bullets?: Array<string>;
    /**
     * Key signals or insights identified
     */
    signals?: Array<string>;
    /**
     * Risks or caveats mentioned in the report
     */
    risks?: Array<string>;
    /**
     * Overall sentiment label
     */
    sentiment_label?: ReportCreateDto.sentiment_label;
    /**
     * Numeric sentiment score (e.g., -1..1 or 0..1 depending on model)
     */
    sentiment_score?: number;
    /**
     * Forward-looking outlook text
     */
    outlook?: string;
    /**
     * Citations with documentId and quote
     */
    support?: Array<Record<string, any>>;
};
export namespace ReportCreateDto {
    /**
     * Overall sentiment label
     */
    export enum sentiment_label {
        BEARISH = 'bearish',
        NEUTRAL = 'neutral',
        BULLISH = 'bullish',
    }
}

